### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50


config:
  debug: true                     # recv msg that i send for debugging
  odom_convert: true              # convert odom to posestamped using odom_convert_node
  monitor_node: true              # check recv rate
  warn_threshold: 3               # if recv rate smaller than max_freq-warn_threashold, then warn
  monitor_rate_hz: 500            # it must be greater than max_freq
  
topics:
- topic_name: /odom_test
  msg_type: nav_msgs/Odometry     # ROS message type (rosmsg style)
  srcIP: 
  - all                        # send device
  srcPort: 3000                   # ports of send_topics should be different
  max_freq: 30.6                    # max send frequent(hz)
  dstIP: 
  - all_drone
  prefix: true                   

- topic_name: /chatter1
  msg_type: std_msgs/String     # ROS message type (rosmsg style)
  srcIP: 
  - groundStation0                        # send device
  srcPort: 2000                   # ports of send_topics should be different
  max_freq: 0.2                    # max send frequent(hz)
  dstIP: 
  - groundStation0
  prefix: true                   

- topic_name: /goalset_test
  msg_type: quadrotor_msgs/GoalSet
  srcIP:
    - groundStation0
  srcPort: 3031
  max_freq: 10
  dstIP:
    - all_drone
  prefix: true
  same_prefix: true


