
config:
  debug: false                    # for debug only
  odom_convert: true              # convert odom to posestamped using odom_convert_node
  monitor_node: true              # check recv rate
  warn_threshold: 3               # if recv rate smaller than max_freq-warn_threashold, then warn
  monitor_rate_hz: 500            # it must be greater than max_freq

services:
  # --------- Services ---------- #
  - srv_name: /add_two_ints
    srv_type: swarm_ros_bridge/AddTwoInts
    serverIp: drone0
    clientIp:
      - drone1
      - drone2
    srcPort: 2000
    prefix: true

topics:
# --------- Swarm Info ---------- #
- topic_name: /drone_0_ego_planner_node/rc_ctrl_marker
  msg_type: visualization_msgs/MarkerArray
  srcIP:
    - drone0
  srcPort: 3001
  max_freq: 20
  dstIP:
    - groundStation0
  prefix: false
  same_prefix: false

- topic_name: /camera/image
  msg_type: sensor_msgs/Image
  imgResizeRate: 1.0
  srcIP:
    - drone1
  srcPort: 3005
  max_freq: 24
  dstIP:
    - groundStation0
  prefix: false
  same_prefix: false








